OBJS = SumOfDigits.o
CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

SumOfDigits : $(OBJS)
		   $(CC) $(LFLAGS) $(OBJS) -o SumOfDigits

SumOfDigits.o : SumOfDigits.cpp
			 $(CC) $(CFLAGS) SumOfDigits.cpp
			 
clean:
	\rm *.o *~ SumOfDigits